import { test, expect } from '@playwright/test';
test('delete key and downward drop support undo including last element', async ({ page }) => {
  await page.goto('/');
  const add = page.getByRole('button', { name: '加入 GFA-2-30-30', exact: true });
  await add.click();
  await add.click();
  const rows = page.locator('.sequence-row');
  await expect(rows).toHaveCount(2);
  await rows.first().click();
  await page.keyboard.press('Delete');
  await expect(rows).toHaveCount(1);
  await page.keyboard.press('Control+z');
  await expect(rows).toHaveCount(2);
  const search = page.getByRole('textbox', { name: '搜索设计元件' });
  await search.fill('abc');
  await page.keyboard.press('Delete');
  await expect(rows).toHaveCount(2);
  await search.fill('');
  async function dragDiagram() {
    const box = await page.locator('[data-element-hitbox]').first().boundingBox();
    await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
    await page.mouse.down();
    await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2 + 10, { steps: 3 });
    const zone = page.locator('[data-element-delete-zone]');
    await expect(zone).toBeVisible();
    const z = await zone.boundingBox();
    await page.mouse.move(z.x + z.width / 2, z.y + z.height / 2, { steps: 10 });
    const floating = page.locator('[data-diagram-floating]');
    await expect(floating).toBeVisible();
    const preview = await floating.boundingBox();
    expect(z.y + z.height / 2).toBeGreaterThan(preview.y);
    expect(z.y + z.height / 2).toBeLessThan(preview.y + preview.height);
    expect(z.x + z.width / 2).toBeGreaterThan(preview.x - 1);
    expect(z.x + z.width / 2).toBeLessThan(preview.x + preview.width + 1);
    await page.mouse.up();
    await expect(floating).toHaveCount(0);
  }
  await dragDiagram();
  await expect(rows).toHaveCount(1);
  await dragDiagram();
  await expect(rows).toHaveCount(0);
  await page.keyboard.press('Control+z');
  await expect(rows).toHaveCount(1);
  const row = await rows.first().boundingBox();
  await page.mouse.move(row.x + 80, row.y + row.height / 2);
  await page.mouse.down();
  await page.mouse.move(row.x + 90, row.y + row.height / 2 + 10, { steps: 5 });
  const zone = page.locator('[data-element-delete-zone]');
  await expect(zone).toBeVisible();
  const z = await zone.boundingBox();
  await page.mouse.move(z.x + z.width / 2, z.y + z.height / 2, { steps: 10 });
  await page.mouse.up();
  await expect(rows).toHaveCount(0);
});

test('blank click and Escape clear selection without changing the design', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: '加入 GFA-2-30-30', exact: true }).click();
  const rows = page.locator('.sequence-row');
  await expect(rows.first()).toHaveClass(/selected/);
  await page.locator('.drawing').click({ position: { x: 10, y: 10 } });
  await expect(page.locator('.sequence-row.selected')).toHaveCount(0);
  await page.keyboard.press('Delete');
  await expect(rows).toHaveCount(1);
  await rows.first().click();
  await expect(rows.first()).toHaveClass(/selected/);
  await page.keyboard.press('Escape');
  await expect(page.locator('.sequence-row.selected')).toHaveCount(0);
  await page.keyboard.press('Delete');
  await expect(rows).toHaveCount(1);
  await page.locator('[data-element-hitbox]').first().click();
  await expect(rows.first()).toHaveClass(/selected/);
  await page.getByRole('button', { name: '查看选中元件', exact: true }).click();
  await expect(rows.first()).toHaveClass(/selected/);
});
